#ifndef LF2COMMON_H
#define LF2COMMON_H

#define LF2_DEPTH_HORIZONTAL_FOV 70.6
#define LF2_DEPTH_VERTICAL_FOV 60

#define LF2_COLOR_HORIZONTAL_FOV 84.1
#define LF2_COLOR_VERTICAL_FOV 53.8

#endif // LF2COMMON_H
